import { useEffect, useMemo, useState } from 'react';
import api from '../api';
import { useUoc } from '../components/UoCContext';
import { useAuth } from '../components/AuthContext';

type Tab='overview'|'GAP'|'MAINTENANCE'|'PLANT_HEALTH'|'DOCUMENT'|'VISIT'|'EVALUATION';
const labels:Record<Tab,string>={overview:'Plantaciones',GAP:'Buenas prácticas agrícolas',MAINTENANCE:'Mantenimiento',PLANT_HEALTH:'Sanidad vegetal',DOCUMENT:'Control documental',VISIT:'Visitas y auditorías',EVALUATION:'Evaluaciones P&C'};
export default function PlantationCompliance(){
  const {selectedUocId}=useUoc();const{user}=useAuth();const[plots,setPlots]=useState<any[]>([]);const[activities,setActivities]=useState<any[]>([]);const[sources,setSources]=useState<any[]>([]);const[tab,setTab]=useState<Tab>('overview');const[showPlot,setShowPlot]=useState(false);const[showActivity,setShowActivity]=useState(false);const[error,setError]=useState('');
  const[plotForm,setPlotForm]=useState({supplySourceId:'',name:'',farmName:'',area:'',plantedArea:'',estimatedProductionMt:'',eligibilityStatus:'PENDING',certificationStatus:'PENDING'});
  const[activityForm,setActivityForm]=useState({farmPlotId:'',title:'',description:'',status:'PENDING',score:'',isCritical:false,responsible:'',activityDate:''});
  const canEdit=['ADMIN','MANAGER','AUDITOR'].includes(user?.role||'');
  const load=()=>{if(!selectedUocId||selectedUocId==='all')return;const params={uocId:selectedUocId};Promise.all([api.get('/rspo/farm-plots',{params}),api.get('/rspo/plantation-activities',{params}),api.get('/rspo/supply-sources',{params})]).then(([a,b,c])=>{setPlots(a.data);setActivities(b.data);setSources(c.data);}).catch(e=>setError(e.response?.data?.error||'No fue posible cargar plantaciones.'));};useEffect(load,[selectedUocId]);
  const filtered=useMemo(()=>tab==='overview'?[]:activities.filter(a=>a.category===tab),[tab,activities]);
  const createPlot=async(e:React.FormEvent)=>{e.preventDefault();await api.post('/rspo/farm-plots',{...plotForm,uocId:selectedUocId,area:Number(plotForm.area),plantedArea:Number(plotForm.plantedArea),estimatedProductionMt:Number(plotForm.estimatedProductionMt)});setShowPlot(false);load();};
  const createActivity=async(e:React.FormEvent)=>{e.preventDefault();await api.post('/rspo/plantation-activities',{...activityForm,uocId:selectedUocId,category:tab,score:activityForm.score===''?null:Number(activityForm.score)});setShowActivity(false);load();};
  if(!selectedUocId||selectedUocId==='all')return <div className="empty-state card"><h3>Seleccione una UoC</h3><p>El cumplimiento agrícola se calcula desde registros de una UoC autorizada.</p></div>;
  return <div className="flex-col gap-5 animate-fade-in">
    <div className="flex gap-1 flex-wrap">{(Object.keys(labels) as Tab[]).map(id=><button key={id} className={`btn btn-sm ${tab===id?'btn-primary':'btn-secondary'}`} onClick={()=>setTab(id)}>{labels[id]}</button>)}</div>
    {error&&<div className="integration-note">{error}</div>}
    {tab==='overview'?<><div className="stats-grid"><div className="card"><small>Plantaciones / lotes</small><div className="stat-value-lg">{plots.length}</div></div><div className="card"><small>Cumplimiento promedio</small><div className="stat-value-lg">{plots.length?Math.round(plots.reduce((s,p)=>s+Number(p.compliance||0),0)/plots.length):0}%</div></div><div className="card"><small>Requisitos críticos abiertos</small><div className="stat-value-lg">{plots.reduce((s,p)=>s+Number(p.criticalRequirements||0),0)}</div></div></div><div className="flex-between"><h2 className="text-xl font-bold">Ficha individual de plantaciones</h2>{user?.role!=='USER'&&<button className="btn btn-primary" onClick={()=>setShowPlot(v=>!v)}>+ Nueva plantación</button>}</div>{showPlot&&<form className="card form-grid" onSubmit={createPlot}><select required className="form-select" value={plotForm.supplySourceId} onChange={e=>setPlotForm({...plotForm,supplySourceId:e.target.value})}><option value="">Fuente de suministro</option>{sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input required className="form-input" placeholder="Nombre del lote" value={plotForm.name} onChange={e=>setPlotForm({...plotForm,name:e.target.value})}/><input className="form-input" placeholder="Nombre de plantación/predio" value={plotForm.farmName} onChange={e=>setPlotForm({...plotForm,farmName:e.target.value})}/><input type="number" className="form-input" placeholder="Área ha" value={plotForm.area} onChange={e=>setPlotForm({...plotForm,area:e.target.value})}/><input type="number" className="form-input" placeholder="Producción estimada TM" value={plotForm.estimatedProductionMt} onChange={e=>setPlotForm({...plotForm,estimatedProductionMt:e.target.value})}/><button className="btn btn-primary">Guardar</button></form>}{plots.length===0?<div className="empty-state card"><h3>No hay plantaciones registradas</h3><p>Agregue la primera ficha individual para iniciar evaluaciones reales.</p></div>:<div className="card p-0"><div className="table-responsive"><table className="w-full"><thead><tr><th>Plantación / lote</th><th>Fuente</th><th>Área</th><th>Elegibilidad</th><th>Certificación</th><th>Cumplimiento</th><th>Críticos</th></tr></thead><tbody>{plots.map(p=><tr key={p.id}><td><strong>{p.farmName||p.name}</strong><br/><small>{p.name}</small></td><td>{p.sourceName}</td><td>{Number(p.area)} ha</td><td>{p.eligibilityStatus}</td><td>{p.certificationStatus}</td><td>{Number(p.compliance||0)}%</td><td>{Number(p.criticalRequirements||0)}</td></tr>)}</tbody></table></div></div>}</>:<>
      <div className="flex-between"><h2 className="text-xl font-bold">{labels[tab]}</h2>{canEdit&&<button className="btn btn-primary" onClick={()=>setShowActivity(v=>!v)}>+ Nuevo registro</button>}</div>
      {showActivity&&<form className="card form-grid" onSubmit={createActivity}><select required className="form-select" value={activityForm.farmPlotId} onChange={e=>setActivityForm({...activityForm,farmPlotId:e.target.value})}><option value="">Plantación / lote</option>{plots.map(p=><option key={p.id} value={p.id}>{p.farmName||p.name} — {p.name}</option>)}</select><input required className="form-input" placeholder="Actividad o requisito" value={activityForm.title} onChange={e=>setActivityForm({...activityForm,title:e.target.value})}/><input className="form-input" placeholder="Responsable" value={activityForm.responsible} onChange={e=>setActivityForm({...activityForm,responsible:e.target.value})}/>{tab==='EVALUATION'&&<input type="number" min="0" max="100" className="form-input" placeholder="Puntaje %" value={activityForm.score} onChange={e=>setActivityForm({...activityForm,score:e.target.value})}/>}<label className="form-label"><input type="checkbox" checked={activityForm.isCritical} onChange={e=>setActivityForm({...activityForm,isCritical:e.target.checked})}/> Requisito crítico</label><input type="date" className="form-input" value={activityForm.activityDate} onChange={e=>setActivityForm({...activityForm,activityDate:e.target.value})}/><button className="btn btn-primary">Guardar</button></form>}
      {filtered.length===0?<div className="empty-state card"><h3>Sin registros</h3><p>No hay información persistida para esta categoría.</p></div>:<div className="card p-0"><div className="table-responsive"><table className="w-full"><thead><tr><th>Plantación</th><th>Actividad</th><th>Responsable</th><th>Fecha</th><th>Estado</th><th>Puntaje</th><th>Crítico</th></tr></thead><tbody>{filtered.map(a=><tr key={a.id}><td>{a.farmName||a.plotName}</td><td>{a.title}</td><td>{a.responsible||'—'}</td><td>{a.activityDate?String(a.activityDate).slice(0,10):'—'}</td><td>{a.status}</td><td>{a.score??'—'}</td><td>{a.isCritical?'Sí':'No'}</td></tr>)}</tbody></table></div></div>}</>}
  </div>;
}
