-- schema.sql
-- DDL para la Base de Datos del Sistema Cert-TechCol (MySQL)

CREATE TABLE IF NOT EXISTS User (
  id VARCHAR(36) PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  role ENUM('ADMIN', 'MANAGER', 'AUDITOR', 'USER') DEFAULT 'USER',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Standard (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  fullName VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  color VARCHAR(50) NOT NULL,
  icon VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Document (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type ENUM('POLICY', 'PROCEDURE', 'RECORD', 'MANUAL', 'CONTRACT', 'REPORT') NOT NULL,
  standardId VARCHAR(50) NOT NULL,
  status ENUM('REVIEWED', 'PENDING', 'ISSUES_FOUND', 'EXPIRED') DEFAULT 'PENDING',
  uploadDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  reviewer VARCHAR(255) NULL,
  aiScore FLOAT NULL,
  size VARCHAR(50) NOT NULL,
  version VARCHAR(50) NOT NULL,
  FOREIGN KEY (standardId) REFERENCES Standard(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Requirement (
  id VARCHAR(36) PRIMARY KEY,
  clause VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  status ENUM('COMPLIANT', 'NON_COMPLIANT', 'PARTIAL', 'PENDING') DEFAULT 'PENDING',
  evidenceCount INT DEFAULT 0,
  standardId VARCHAR(50) NOT NULL,
  FOREIGN KEY (standardId) REFERENCES Standard(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AIFinding (
  id VARCHAR(36) PRIMARY KEY,
  type ENUM('GAP', 'RECOMMENDATION', 'RISK', 'IMPROVEMENT') NOT NULL,
  severity ENUM('HIGH', 'MEDIUM', 'LOW') NOT NULL,
  description TEXT NOT NULL,
  clause VARCHAR(50) NULL,
  documentId VARCHAR(36) NOT NULL,
  FOREIGN KEY (documentId) REFERENCES Document(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Risk (
  id VARCHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR(255) NOT NULL,
  standardId VARCHAR(50) NOT NULL,
  probability INT NOT NULL,
  impact INT NOT NULL,
  level ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW') NOT NULL,
  status ENUM('OPEN', 'MITIGATED', 'ACCEPTED', 'CLOSED') DEFAULT 'OPEN',
  owner VARCHAR(255) NOT NULL,
  createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (standardId) REFERENCES Standard(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Evidence (
  id VARCHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  standardId VARCHAR(50) NOT NULL,
  clause VARCHAR(50) NOT NULL,
  type ENUM('DOCUMENT', 'PHOTO', 'RECORD', 'REPORT', 'CERTIFICATE') NOT NULL,
  status ENUM('VALID', 'EXPIRED', 'PENDING_REVIEW') DEFAULT 'PENDING_REVIEW',
  uploadDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expiryDate TIMESTAMP NULL,
  FOREIGN KEY (standardId) REFERENCES Standard(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Audit (
  id VARCHAR(191) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  date TIMESTAMP NOT NULL,
  type ENUM('INTERNAL', 'EXTERNAL', 'CERTIFICATION') NOT NULL,
  auditorName VARCHAR(255) NOT NULL,
  status ENUM('SCHEDULED', 'IN_PROGRESS', 'CLOSED') DEFAULT 'SCHEDULED',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS NonConformance (
  id VARCHAR(191) PRIMARY KEY,
  auditId VARCHAR(191) NOT NULL,
  requirementId VARCHAR(191) NOT NULL,
  type ENUM('MAJOR_NC', 'MINOR_NC', 'OBSERVATION', 'OPPORTUNITY') NOT NULL,
  description TEXT NOT NULL,
  status ENUM('OPEN', 'PENDING_AI_REVIEW', 'CLOSED', 'REJECTED_BY_AI') DEFAULT 'OPEN',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (auditId) REFERENCES Audit(id) ON DELETE CASCADE,
  FOREIGN KEY (requirementId) REFERENCES Requirement(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ActionPlan (
  id VARCHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  type ENUM('CORRECTIVE', 'PREVENTIVE', 'IMPROVEMENT') NOT NULL,
  status ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE') DEFAULT 'PENDING',
  priority ENUM('HIGH', 'MEDIUM', 'LOW') NOT NULL,
  assigneeId VARCHAR(191) NOT NULL,
  dueDate TIMESTAMP NOT NULL,
  createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  progress INT DEFAULT 0,
  nonConformanceId VARCHAR(191) NULL,
  evidenceName VARCHAR(255) NULL,
  aiFeedback TEXT NULL,
  riskId VARCHAR(36) NULL,
  FOREIGN KEY (assigneeId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (nonConformanceId) REFERENCES NonConformance(id) ON DELETE SET NULL,
  FOREIGN KEY (riskId) REFERENCES Risk(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Activity (
  id VARCHAR(36) PRIMARY KEY,
  action VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  userId VARCHAR(36) NOT NULL,
  standardId VARCHAR(50) NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (standardId) REFERENCES Standard(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS CertificationUnit (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  companyName VARCHAR(255) NOT NULL,
  country VARCHAR(100) NOT NULL DEFAULT 'Colombia',
  area DECIMAL(12,2) DEFAULT 0,
  status ENUM('ACTIVE', 'INACTIVE', 'CERTIFIED', 'AUDIT_PENDING') DEFAULT 'ACTIVE',
  managerName VARCHAR(255),
  managerEmail VARCHAR(255),
  certifiedSince DATE NULL,
  nextAuditDate DATE NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SccTransaction (
  id VARCHAR(36) PRIMARY KEY,
  uocId VARCHAR(36) NOT NULL,
  type ENUM('RECEPTION', 'PRODUCTION', 'SALE', 'TRANSFER') NOT NULL,
  productType ENUM('RFF', 'CPO', 'PK', 'PKO', 'PKE', 'RBDPO', 'RBDPL', 'PFAD') NOT NULL,
  supplyModel ENUM('IP', 'SG', 'MB', 'BC') NOT NULL,
  volumeMt DECIMAL(12,3) NOT NULL,
  batchRef VARCHAR(100),
  counterparty VARCHAR(255),
  documentRef VARCHAR(255),
  greenhouseGas FLOAT DEFAULT 0,
  transactionDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  notes TEXT,
  createdBy VARCHAR(255),
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Stakeholder (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type ENUM('COMMUNITY', 'GOVERNMENT', 'NGO', 'WORKER', 'SUPPLIER', 'BUYER', 'ACADEMIC', 'MEDIA', 'OTHER') NOT NULL DEFAULT 'OTHER',
  location VARCHAR(255),
  interest TEXT,
  influence ENUM('HIGH', 'MEDIUM', 'LOW') NOT NULL DEFAULT 'MEDIUM',
  engagementChannel VARCHAR(255),
  lastEngagement DATE NULL,
  nextEngagement DATE NULL,
  responsibleName VARCHAR(255),
  responsibleEmail VARCHAR(255),
  status ENUM('ACTIVE', 'INACTIVE', 'PENDING') DEFAULT 'ACTIVE',
  notes TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
