-- schema.sql
-- DDL para la Base de Datos del Sistema Cert-TechCol (MySQL)

CREATE TABLE IF NOT EXISTS User (
  id VARCHAR(36) PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  role ENUM('ADMIN', 'MANAGER', 'AUDITOR', 'USER') DEFAULT 'USER',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Standard (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  fullName VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  color VARCHAR(50) NOT NULL,
  icon VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Document (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type ENUM('POLICY', 'PROCEDURE', 'RECORD', 'MANUAL', 'CONTRACT', 'REPORT') NOT NULL,
  standardId VARCHAR(50) NOT NULL,
  status ENUM('REVIEWED', 'PENDING', 'ISSUES_FOUND', 'EXPIRED') DEFAULT 'PENDING',
  uploadDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  reviewer VARCHAR(255) NULL,
  aiScore FLOAT NULL,
  size VARCHAR(50) NOT NULL,
  version VARCHAR(50) NOT NULL,
  FOREIGN KEY (standardId) REFERENCES Standard(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Requirement (
  id VARCHAR(36) PRIMARY KEY,
  clause VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  status ENUM('COMPLIANT', 'NON_COMPLIANT', 'PARTIAL', 'PENDING') DEFAULT 'PENDING',
  evidenceCount INT DEFAULT 0,
  standardId VARCHAR(50) NOT NULL,
  FOREIGN KEY (standardId) REFERENCES Standard(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AIFinding (
  id VARCHAR(36) PRIMARY KEY,
  type ENUM('GAP', 'RECOMMENDATION', 'RISK', 'IMPROVEMENT') NOT NULL,
  severity ENUM('HIGH', 'MEDIUM', 'LOW') NOT NULL,
  description TEXT NOT NULL,
  clause VARCHAR(50) NULL,
  documentId VARCHAR(36) NOT NULL,
  FOREIGN KEY (documentId) REFERENCES Document(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Risk (
  id VARCHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR(255) NOT NULL,
  standardId VARCHAR(50) NOT NULL,
  probability INT NOT NULL,
  impact INT NOT NULL,
  level ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW') NOT NULL,
  status ENUM('OPEN', 'MITIGATED', 'ACCEPTED', 'CLOSED') DEFAULT 'OPEN',
  owner VARCHAR(255) NOT NULL,
  createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (standardId) REFERENCES Standard(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Evidence (
  id VARCHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  standardId VARCHAR(50) NOT NULL,
  clause VARCHAR(50) NOT NULL,
  type ENUM('DOCUMENT', 'PHOTO', 'RECORD', 'REPORT', 'CERTIFICATE') NOT NULL,
  status ENUM('VALID', 'EXPIRED', 'PENDING_REVIEW') DEFAULT 'PENDING_REVIEW',
  uploadDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expiryDate TIMESTAMP NULL,
  FOREIGN KEY (standardId) REFERENCES Standard(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ActionPlan (
  id VARCHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  type ENUM('CORRECTIVE', 'PREVENTIVE', 'IMPROVEMENT') NOT NULL,
  status ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE') DEFAULT 'PENDING',
  priority ENUM('HIGH', 'MEDIUM', 'LOW') NOT NULL,
  assigneeId VARCHAR(36) NOT NULL,
  dueDate TIMESTAMP NOT NULL,
  createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  progress INT DEFAULT 0,
  FOREIGN KEY (assigneeId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Activity (
  id VARCHAR(36) PRIMARY KEY,
  action VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  userId VARCHAR(36) NOT NULL,
  standardId VARCHAR(50) NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (standardId) REFERENCES Standard(id) ON DELETE SET NULL
);
