-- schema.sql
-- Complete DDL Schema for Cert-TechCol (RSPO TECH) Database in MySQL

CREATE TABLE IF NOT EXISTS User (
  id VARCHAR(36) PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  role ENUM('ADMIN', 'MANAGER', 'AUDITOR', 'USER') DEFAULT 'USER',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Standard (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  fullName VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  color VARCHAR(50) NOT NULL,
  icon VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CertificationUnit (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  companyName VARCHAR(255) NOT NULL,
  country VARCHAR(100) NOT NULL DEFAULT 'Colombia',
  area DECIMAL(12,2) DEFAULT 0,
  status ENUM('ACTIVE', 'INACTIVE', 'CERTIFIED', 'AUDIT_PENDING') DEFAULT 'ACTIVE',
  managerName VARCHAR(255),
  managerEmail VARCHAR(255),
  certifiedSince DATE NULL,
  nextAuditDate DATE NULL,
  type ENUM('MIXED','PLANTATION','MILL','SMALLHOLDERS') DEFAULT 'MIXED',
  appliesAll BOOLEAN DEFAULT TRUE,
  applicablePrinciples JSON NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS UserCertificationUnit (
  userId VARCHAR(36) NOT NULL,
  uocId VARCHAR(36) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (userId, uocId),
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Document (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type ENUM('POLICY', 'PROCEDURE', 'RECORD', 'MANUAL', 'CONTRACT', 'REPORT') NOT NULL,
  standardId VARCHAR(50) NOT NULL,
  status ENUM('REVIEWED', 'PENDING', 'ISSUES_FOUND', 'EXPIRED') DEFAULT 'PENDING',
  uploadDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  reviewer VARCHAR(255) NULL,
  aiScore FLOAT NULL,
  size VARCHAR(50) NOT NULL,
  version VARCHAR(50) NOT NULL,
  uocId VARCHAR(36) NULL,
  FOREIGN KEY (standardId) REFERENCES Standard(id) ON DELETE CASCADE,
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Requirement (
  id VARCHAR(36) PRIMARY KEY,
  clause VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  status ENUM('COMPLIANT', 'NON_COMPLIANT', 'PARTIAL', 'PENDING') DEFAULT 'PENDING',
  evidenceCount INT DEFAULT 0,
  standardId VARCHAR(50) NOT NULL,
  uocId VARCHAR(36) NULL,
  FOREIGN KEY (standardId) REFERENCES Standard(id) ON DELETE CASCADE,
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS AIFinding (
  id VARCHAR(36) PRIMARY KEY,
  type ENUM('GAP', 'RECOMMENDATION', 'RISK', 'IMPROVEMENT') NOT NULL,
  severity ENUM('HIGH', 'MEDIUM', 'LOW') NOT NULL,
  description TEXT NOT NULL,
  clause VARCHAR(50) NULL,
  documentId VARCHAR(36) NOT NULL,
  FOREIGN KEY (documentId) REFERENCES Document(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Risk (
  id VARCHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR(255) NOT NULL,
  standardId VARCHAR(50) NOT NULL,
  probability INT NOT NULL,
  impact INT NOT NULL,
  level ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW') NOT NULL,
  status ENUM('OPEN', 'MITIGATED', 'ACCEPTED', 'CLOSED') DEFAULT 'OPEN',
  owner VARCHAR(255) NOT NULL,
  uocId VARCHAR(36) NULL,
  createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (standardId) REFERENCES Standard(id) ON DELETE CASCADE,
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS SupplySource (
  id VARCHAR(36) PRIMARY KEY,
  uocId VARCHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL,
  identifier VARCHAR(100) NOT NULL,
  sourceType ENUM('PROPRIETARY', 'ASSOCIATED', 'INDEPENDENT', 'SMALLHOLDERS') NOT NULL,
  totalArea DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  plantedArea DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  certifiedArea DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  polygonReference VARCHAR(255) NULL,
  polygonStatus ENUM('PENDING', 'VALIDATED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
  riskLevel ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW') NOT NULL DEFAULT 'MEDIUM',
  eligibilityStatus ENUM('ELIGIBLE', 'INELIGIBLE', 'PENDING') NOT NULL DEFAULT 'PENDING',
  certificationStatus ENUM('CERTIFIED', 'IN_PROCESS', 'NON_CERTIFIED', 'PENDING') NOT NULL DEFAULT 'PENDING',
  responsible VARCHAR(255) NULL,
  lastEvaluation DATE NULL,
  expiryDate DATE NULL,
  notes TEXT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_supply_uoc (uocId),
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FarmPlot (
  id VARCHAR(36) PRIMARY KEY,
  uocId VARCHAR(36) NOT NULL,
  supplySourceId VARCHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL,
  farmName VARCHAR(255) NULL,
  area DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  plantedArea DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  estimatedProductionMt DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  eligibilityStatus ENUM('ELIGIBLE', 'INELIGIBLE', 'PENDING') NOT NULL DEFAULT 'PENDING',
  certificationStatus ENUM('CERTIFIED', 'IN_PROCESS', 'NON_CERTIFIED', 'PENDING') NOT NULL DEFAULT 'PENDING',
  polygonReference VARCHAR(255) NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_farmplot_uoc_source (uocId, supplySourceId),
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE,
  FOREIGN KEY (supplySourceId) REFERENCES SupplySource(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SupplySourceHistory (
  id VARCHAR(36) PRIMARY KEY,
  supplySourceId VARCHAR(36) NOT NULL,
  uocId VARCHAR(36) NOT NULL,
  changedBy VARCHAR(36) NOT NULL,
  changesJson LONGTEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_supply_history (supplySourceId, createdAt),
  FOREIGN KEY (supplySourceId) REFERENCES SupplySource(id) ON DELETE CASCADE,
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE,
  FOREIGN KEY (changedBy) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS PlantationActivity (
  id VARCHAR(36) PRIMARY KEY,
  uocId VARCHAR(36) NOT NULL,
  farmPlotId VARCHAR(36) NOT NULL,
  category ENUM('MONITORING', 'HEALTH', 'AGRONOMIC', 'EVALUATION') NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'SCHEDULED',
  score DECIMAL(5,2) NULL,
  isCritical TINYINT(1) NOT NULL DEFAULT 0,
  responsible VARCHAR(255) NULL,
  scheduledDate DATE NULL,
  completedDate DATE NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_plantation_act_uoc_plot (uocId, farmPlotId, category),
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE,
  FOREIGN KEY (farmPlotId) REFERENCES FarmPlot(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FarmPlotSoilStudy (
  id VARCHAR(36) PRIMARY KEY,
  uocId VARCHAR(36) NOT NULL,
  farmPlotId VARCHAR(36) NOT NULL,
  originalFileName VARCHAR(255) NOT NULL,
  kmlText MEDIUMTEXT NOT NULL,
  geometryJson LONGTEXT NOT NULL,
  fieldContext TEXT NULL,
  studyJson LONGTEXT NOT NULL,
  analysisMode ENUM('AI','LOCAL') NOT NULL DEFAULT 'LOCAL',
  model VARCHAR(100) NULL,
  createdBy VARCHAR(36) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_soil_study_plot (uocId, farmPlotId, createdAt),
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE,
  FOREIGN KEY (farmPlotId) REFERENCES FarmPlot(id) ON DELETE CASCADE,
  FOREIGN KEY (createdBy) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS Delivery (
  id VARCHAR(36) PRIMARY KEY,
  uocId VARCHAR(36) NOT NULL,
  supplySourceId VARCHAR(36) NOT NULL,
  farmPlotId VARCHAR(36) NULL,
  remisionNumber VARCHAR(100) NOT NULL,
  weighbridgeTicket VARCHAR(100) NULL,
  driverName VARCHAR(255) NULL,
  licensePlate VARCHAR(50) NULL,
  grossWeightKg DECIMAL(12,3) NOT NULL,
  tareWeightKg DECIMAL(12,3) NOT NULL,
  netWeightKg DECIMAL(12,3) NOT NULL,
  volumeMt DECIMAL(12,3) NOT NULL,
  eligibilityStatus ENUM('ELIGIBLE', 'INELIGIBLE', 'PENDING') NOT NULL DEFAULT 'PENDING',
  certificationStatus ENUM('CERTIFIED', 'IN_PROCESS', 'NON_CERTIFIED', 'PENDING') NOT NULL DEFAULT 'PENDING',
  deliveryDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  receivedBy VARCHAR(255) NULL,
  notes TEXT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_delivery_uoc_source (uocId, supplySourceId, deliveryDate),
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE,
  FOREIGN KEY (supplySourceId) REFERENCES SupplySource(id) ON DELETE CASCADE,
  FOREIGN KEY (farmPlotId) REFERENCES FarmPlot(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Evidence (
  id VARCHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  standardId VARCHAR(50) NOT NULL,
  clause VARCHAR(50) NOT NULL,
  type ENUM('DOCUMENT', 'PHOTO', 'RECORD', 'REPORT', 'CERTIFICATE') NOT NULL,
  status ENUM('VALID', 'EXPIRED', 'PENDING_REVIEW') DEFAULT 'PENDING_REVIEW',
  uploadDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expiryDate TIMESTAMP NULL,
  uocId VARCHAR(36) NULL,
  companyName VARCHAR(255) NULL,
  supplySourceId VARCHAR(36) NULL,
  farmPlotId VARCHAR(36) NULL,
  requirementId VARCHAR(36) NULL,
  indicator VARCHAR(255) NULL,
  responsible VARCHAR(255) NULL,
  fileName VARCHAR(255) NULL,
  originalFileName VARCHAR(255) NULL,
  mimeType VARCHAR(100) NULL,
  observations TEXT NULL,
  reviewedBy VARCHAR(36) NULL,
  reviewedAt TIMESTAMP NULL,
  FOREIGN KEY (standardId) REFERENCES Standard(id) ON DELETE CASCADE,
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE SET NULL,
  FOREIGN KEY (supplySourceId) REFERENCES SupplySource(id) ON DELETE SET NULL,
  FOREIGN KEY (farmPlotId) REFERENCES FarmPlot(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Audit (
  id VARCHAR(191) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  date TIMESTAMP NOT NULL,
  type ENUM('INTERNAL', 'EXTERNAL', 'CERTIFICATION') NOT NULL,
  auditorName VARCHAR(255) NOT NULL,
  status ENUM('SCHEDULED', 'IN_PROGRESS', 'CLOSED') DEFAULT 'SCHEDULED',
  uocId VARCHAR(36) NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS NonConformance (
  id VARCHAR(191) PRIMARY KEY,
  auditId VARCHAR(191) NOT NULL,
  requirementId VARCHAR(191) NOT NULL,
  type ENUM('MAJOR_NC', 'MINOR_NC', 'OBSERVATION', 'OPPORTUNITY') NOT NULL,
  description TEXT NOT NULL,
  status ENUM('OPEN', 'PENDING_AI_REVIEW', 'CLOSED', 'REJECTED_BY_AI') DEFAULT 'OPEN',
  uocId VARCHAR(36) NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (auditId) REFERENCES Audit(id) ON DELETE CASCADE,
  FOREIGN KEY (requirementId) REFERENCES Requirement(id) ON DELETE CASCADE,
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ActionPlan (
  id VARCHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  type ENUM('CORRECTIVE', 'PREVENTIVE', 'IMPROVEMENT') NOT NULL,
  status ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE') DEFAULT 'PENDING',
  priority ENUM('HIGH', 'MEDIUM', 'LOW') NOT NULL,
  assigneeId VARCHAR(191) NOT NULL,
  dueDate TIMESTAMP NOT NULL,
  createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  progress INT DEFAULT 0,
  nonConformanceId VARCHAR(191) NULL,
  evidenceName VARCHAR(255) NULL,
  aiFeedback TEXT NULL,
  riskId VARCHAR(36) NULL,
  brecha TEXT NULL,
  causaRaiz TEXT NULL,
  correccion TEXT NULL,
  eficacia TEXT NULL,
  closedAt TIMESTAMP NULL,
  uocId VARCHAR(36) NULL,
  evidenceId VARCHAR(36) NULL,
  FOREIGN KEY (assigneeId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (nonConformanceId) REFERENCES NonConformance(id) ON DELETE SET NULL,
  FOREIGN KEY (riskId) REFERENCES Risk(id) ON DELETE SET NULL,
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE SET NULL,
  FOREIGN KEY (evidenceId) REFERENCES Evidence(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ActionPlanHistory (
  id VARCHAR(36) PRIMARY KEY,
  actionPlanId VARCHAR(36) NOT NULL,
  uocId VARCHAR(36) NULL,
  changedBy VARCHAR(36) NOT NULL,
  changesJson LONGTEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_ap_history (actionPlanId, createdAt),
  FOREIGN KEY (actionPlanId) REFERENCES ActionPlan(id) ON DELETE CASCADE,
  FOREIGN KEY (changedBy) REFERENCES User(id),
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Activity (
  id VARCHAR(36) PRIMARY KEY,
  action VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  userId VARCHAR(36) NOT NULL,
  standardId VARCHAR(50) NULL,
  uocId VARCHAR(36) NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (standardId) REFERENCES Standard(id) ON DELETE SET NULL,
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS SccTransaction (
  id VARCHAR(36) PRIMARY KEY,
  uocId VARCHAR(36) NOT NULL,
  type ENUM('RECEPTION', 'PRODUCTION', 'SALE', 'TRANSFER') NOT NULL,
  productType ENUM('RFF', 'CPO', 'PK', 'PKO', 'PKE', 'RBDPO', 'RBDPL', 'PFAD') NOT NULL,
  supplyModel ENUM('IP', 'SG', 'MB', 'BC') NOT NULL,
  volumeMt DECIMAL(12,3) NOT NULL,
  batchRef VARCHAR(100),
  counterparty VARCHAR(255),
  documentRef VARCHAR(255),
  greenhouseGas FLOAT DEFAULT 0,
  transactionDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  notes TEXT,
  createdBy VARCHAR(255),
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Stakeholder (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type ENUM('COMMUNITY', 'GOVERNMENT', 'NGO', 'WORKER', 'SUPPLIER', 'BUYER', 'ACADEMIC', 'MEDIA', 'OTHER') NOT NULL DEFAULT 'OTHER',
  location VARCHAR(255),
  interest TEXT,
  influence ENUM('HIGH', 'MEDIUM', 'LOW') NOT NULL DEFAULT 'MEDIUM',
  engagementChannel VARCHAR(255),
  lastEngagement DATE NULL,
  nextEngagement DATE NULL,
  responsibleName VARCHAR(255),
  responsibleEmail VARCHAR(255),
  status ENUM('ACTIVE', 'INACTIVE', 'PENDING') DEFAULT 'ACTIVE',
  notes TEXT,
  uocId VARCHAR(36) NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Alert (
  id VARCHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  type VARCHAR(50) NOT NULL DEFAULT 'info',
  priority VARCHAR(50) NOT NULL DEFAULT 'media',
  action VARCHAR(255) NULL,
  module VARCHAR(100) NULL,
  uocId VARCHAR(36) NULL,
  dismissed TINYINT(1) NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_alert_dismissed_created (dismissed, createdAt),
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS TraceabilityAlert (
  id VARCHAR(36) PRIMARY KEY,
  uocId VARCHAR(36) NOT NULL,
  supplySourceId VARCHAR(36) NULL,
  farmPlotId VARCHAR(36) NULL,
  deliveryId VARCHAR(36) NULL,
  alertType ENUM('EXCEEDED_ESTIMATE', 'INELIGIBLE_ORIGIN', 'GEOLOCATION_MISMATCH', 'DOCUMENTATION_MISSING', 'HIGH_RISK_SOURCE') NOT NULL,
  severity ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW') NOT NULL DEFAULT 'HIGH',
  message TEXT NOT NULL,
  status ENUM('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED') NOT NULL DEFAULT 'OPEN',
  resolvedBy VARCHAR(36) NULL,
  resolutionNotes TEXT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_trace_alert_uoc (uocId, status, severity),
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE,
  FOREIGN KEY (supplySourceId) REFERENCES SupplySource(id) ON DELETE SET NULL,
  FOREIGN KEY (farmPlotId) REFERENCES FarmPlot(id) ON DELETE SET NULL,
  FOREIGN KEY (deliveryId) REFERENCES Delivery(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS PrismaOperation (
  id VARCHAR(36) PRIMARY KEY,
  uocId VARCHAR(36) NOT NULL,
  announcementRef VARCHAR(100) NOT NULL,
  confirmationRef VARCHAR(100) NULL,
  counterparty VARCHAR(255) NOT NULL,
  productType ENUM('RFF', 'CPO', 'PK', 'PKO', 'PKE', 'RBDPO', 'RBDPL', 'PFAD') NOT NULL,
  supplyModel ENUM('IP', 'SG', 'MB', 'BC') NOT NULL,
  announcedVolumeMt DECIMAL(12,3) NOT NULL,
  confirmedVolumeMt DECIMAL(12,3) NULL,
  status ENUM('ANNOUNCED', 'CONFIRMED', 'ADJUSTED', 'CANCELLED', 'REJECTED') NOT NULL DEFAULT 'ANNOUNCED',
  operationDate DATE NOT NULL,
  notes TEXT NULL,
  createdBy VARCHAR(36) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_prisma_op_uoc (uocId, status, operationDate),
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE,
  FOREIGN KEY (createdBy) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS PrismaAdjustment (
  id VARCHAR(36) PRIMARY KEY,
  prismaOperationId VARCHAR(36) NOT NULL,
  uocId VARCHAR(36) NOT NULL,
  previousVolumeMt DECIMAL(12,3) NOT NULL,
  newVolumeMt DECIMAL(12,3) NOT NULL,
  deltaVolumeMt DECIMAL(12,3) NOT NULL,
  reason TEXT NOT NULL,
  adjustedBy VARCHAR(36) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_prisma_adj_op (prismaOperationId, createdAt),
  FOREIGN KEY (prismaOperationId) REFERENCES PrismaOperation(id) ON DELETE CASCADE,
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE,
  FOREIGN KEY (adjustedBy) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS PrismaAttachment (
  id VARCHAR(36) PRIMARY KEY,
  prismaOperationId VARCHAR(36) NOT NULL,
  fileName VARCHAR(255) NOT NULL,
  fileUrl VARCHAR(255) NOT NULL,
  fileSize VARCHAR(50) NULL,
  mimeType VARCHAR(100) NULL,
  uploadedBy VARCHAR(36) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (prismaOperationId) REFERENCES PrismaOperation(id) ON DELETE CASCADE,
  FOREIGN KEY (uploadedBy) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS PlantRecord (
  id VARCHAR(36) PRIMARY KEY,
  uocId VARCHAR(36) NOT NULL,
  section ENUM('contratistas','sst','ambiente','avc','social','negocios') NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  status VARCHAR(50) DEFAULT 'PENDING',
  responsible VARCHAR(255) NULL,
  date DATE NULL,
  meta VARCHAR(255) NULL,
  result VARCHAR(255) NULL,
  extra JSON NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_plant_record_uoc (uocId),
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ApprovalToken (
  id VARCHAR(36) PRIMARY KEY,
  userId VARCHAR(36) NOT NULL,
  documentId VARCHAR(36) NOT NULL,
  tokenHash VARCHAR(255) NOT NULL,
  action ENUM('APPROVE', 'REJECT') NOT NULL,
  status ENUM('PENDING', 'USED', 'EXPIRED') DEFAULT 'PENDING',
  expiresAt TIMESTAMP NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (documentId) REFERENCES Document(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DocumentApproval (
  id VARCHAR(36) PRIMARY KEY,
  documentId VARCHAR(36) NOT NULL,
  userId VARCHAR(36) NOT NULL,
  action ENUM('APPROVED', 'REJECTED') NOT NULL,
  tokenHash VARCHAR(255) NOT NULL,
  comment TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (documentId) REFERENCES Document(id) ON DELETE CASCADE
);
