-- Incremental, non-destructive RSPO TECH core migration.
CREATE TABLE IF NOT EXISTS UserCertificationUnit (
  userId VARCHAR(36) NOT NULL,
  uocId VARCHAR(36) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (userId, uocId),
  CONSTRAINT fk_ucu_user FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  CONSTRAINT fk_ucu_uoc FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE
);

ALTER TABLE CertificationUnit ADD COLUMN IF NOT EXISTS type ENUM('MIXED','PLANTATION','MILL','SMALLHOLDERS') DEFAULT 'MIXED';
ALTER TABLE CertificationUnit ADD COLUMN IF NOT EXISTS appliesAll BOOLEAN DEFAULT TRUE;
ALTER TABLE CertificationUnit ADD COLUMN IF NOT EXISTS applicablePrinciples JSON NULL;

ALTER TABLE ActionPlan ADD COLUMN IF NOT EXISTS brecha TEXT NULL;
ALTER TABLE ActionPlan ADD COLUMN IF NOT EXISTS causaRaiz TEXT NULL;
ALTER TABLE ActionPlan ADD COLUMN IF NOT EXISTS correccion TEXT NULL;
ALTER TABLE ActionPlan ADD COLUMN IF NOT EXISTS eficacia TEXT NULL;
ALTER TABLE ActionPlan ADD COLUMN IF NOT EXISTS closedAt TIMESTAMP NULL;
ALTER TABLE ActionPlan ADD COLUMN IF NOT EXISTS uocId VARCHAR(36) NULL;

CREATE TABLE IF NOT EXISTS SupplySource (
  id VARCHAR(36) PRIMARY KEY,
  uocId VARCHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL,
  identifier VARCHAR(100) NOT NULL,
  sourceType ENUM('OWN','ASSOCIATED','INDEPENDENT','ASSOCIATION','SMALLHOLDER_GROUP','INDIVIDUAL') NOT NULL,
  totalArea DECIMAL(12,2) DEFAULT 0,
  plantedArea DECIMAL(12,2) DEFAULT 0,
  certifiedArea DECIMAL(12,2) DEFAULT 0,
  polygonReference TEXT NULL,
  polygonStatus ENUM('PENDING','VALID','INVALID') DEFAULT 'PENDING',
  riskLevel ENUM('LOW','MEDIUM','HIGH','CRITICAL') DEFAULT 'MEDIUM',
  eligibilityStatus ENUM('ELIGIBLE','CONDITIONAL','INELIGIBLE','PENDING') DEFAULT 'PENDING',
  certificationStatus ENUM('CERTIFIED','CONVENTIONAL','SUSPENDED','PENDING') DEFAULT 'PENDING',
  responsible VARCHAR(255) NULL,
  lastEvaluation DATE NULL,
  expiryDate DATE NULL,
  notes TEXT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_supply_identifier_uoc (uocId, identifier),
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FarmPlot (
  id VARCHAR(36) PRIMARY KEY,
  uocId VARCHAR(36) NOT NULL,
  supplySourceId VARCHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL,
  farmName VARCHAR(255) NULL,
  area DECIMAL(12,2) DEFAULT 0,
  plantedArea DECIMAL(12,2) DEFAULT 0,
  estimatedProductionMt DECIMAL(12,3) DEFAULT 0,
  eligibilityStatus ENUM('ELIGIBLE','CONDITIONAL','INELIGIBLE','PENDING') DEFAULT 'PENDING',
  certificationStatus ENUM('CERTIFIED','CONVENTIONAL','SUSPENDED','PENDING') DEFAULT 'PENDING',
  polygonReference TEXT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE,
  FOREIGN KEY (supplySourceId) REFERENCES SupplySource(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PlantationActivity (
  id VARCHAR(36) PRIMARY KEY,
  uocId VARCHAR(36) NOT NULL,
  farmPlotId VARCHAR(36) NOT NULL,
  category ENUM('GAP','MAINTENANCE','PLANT_HEALTH','INPUT','VISIT','EVALUATION','DOCUMENT') NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  requirementId VARCHAR(36) NULL,
  status VARCHAR(50) DEFAULT 'PENDING',
  score DECIMAL(5,2) NULL,
  isCritical BOOLEAN DEFAULT FALSE,
  responsible VARCHAR(255) NULL,
  activityDate DATE NULL,
  dueDate DATE NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE,
  FOREIGN KEY (farmPlotId) REFERENCES FarmPlot(id) ON DELETE CASCADE,
  FOREIGN KEY (requirementId) REFERENCES Requirement(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS RffDelivery (
  id VARCHAR(36) PRIMARY KEY,
  uocId VARCHAR(36) NOT NULL,
  supplySourceId VARCHAR(36) NOT NULL,
  farmPlotId VARCHAR(36) NULL,
  deliveredAt DATETIME NOT NULL,
  agriculturalLot VARCHAR(100) NULL,
  traceabilityLot VARCHAR(100) NOT NULL,
  vehicle VARCHAR(100) NULL,
  plate VARCHAR(30) NOT NULL,
  driverName VARCHAR(255) NULL,
  weighTicket VARCHAR(100) NOT NULL,
  grossWeightKg DECIMAL(12,3) NOT NULL,
  tareWeightKg DECIMAL(12,3) NOT NULL,
  netWeightKg DECIMAL(12,3) NOT NULL,
  volumeMt DECIMAL(12,3) NOT NULL,
  supplyModel ENUM('IP','SG','MB') NOT NULL,
  fruitCondition ENUM('CERTIFIED','CONVENTIONAL') NOT NULL,
  eligibleAtDelivery BOOLEAN NOT NULL,
  estimatedProductionMt DECIMAL(12,3) DEFAULT 0,
  accumulatedDeliveredMt DECIMAL(12,3) DEFAULT 0,
  varianceMt DECIMAL(12,3) DEFAULT 0,
  documentRef VARCHAR(255) NULL,
  observations TEXT NULL,
  evidenceId VARCHAR(36) NULL,
  status ENUM('ACCEPTED','REVIEW','REJECTED') DEFAULT 'REVIEW',
  sccTransactionId VARCHAR(36) NULL,
  createdBy VARCHAR(36) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_ticket_uoc (uocId, weighTicket),
  UNIQUE KEY uq_trace_lot_uoc (uocId, traceabilityLot),
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE,
  FOREIGN KEY (supplySourceId) REFERENCES SupplySource(id),
  FOREIGN KEY (farmPlotId) REFERENCES FarmPlot(id),
  FOREIGN KEY (evidenceId) REFERENCES Evidence(id) ON DELETE SET NULL,
  FOREIGN KEY (sccTransactionId) REFERENCES SccTransaction(id) ON DELETE SET NULL,
  FOREIGN KEY (createdBy) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS TraceabilityAlert (
  id VARCHAR(36) PRIMARY KEY,
  uocId VARCHAR(36) NOT NULL,
  deliveryId VARCHAR(36) NOT NULL,
  alertType ENUM('INELIGIBLE','OVERPRODUCTION','MISSING_DATA','DUPLICATE','CERTIFICATION_MISMATCH') NOT NULL,
  severity ENUM('LOW','MEDIUM','HIGH','CRITICAL') DEFAULT 'HIGH',
  message TEXT NOT NULL,
  status ENUM('OPEN','RESOLVED','DISMISSED') DEFAULT 'OPEN',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  resolvedAt TIMESTAMP NULL,
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE,
  FOREIGN KEY (deliveryId) REFERENCES RffDelivery(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PrismaOperation (
  id VARCHAR(36) PRIMARY KEY,
  uocId VARCHAR(36) NOT NULL,
  operationType ENUM('SHIPPING_ANNOUNCEMENT','CONFIRMATION','REMOVE','ADJUSTMENT') NOT NULL,
  internalReference VARCHAR(100) NOT NULL,
  prismaReference VARCHAR(100) NULL,
  product VARCHAR(100) NOT NULL,
  supplyModel ENUM('IP','SG','MB','BC') NOT NULL,
  volumeMt DECIMAL(12,3) NOT NULL,
  physicalDate DATE NOT NULL,
  deadline DATE NULL,
  status ENUM('DRAFT','PENDING','CONFIRMED','REMOVED','ADJUSTED','OVERDUE') DEFAULT 'DRAFT',
  counterparty VARCHAR(255) NULL,
  observations TEXT NULL,
  responsibleId VARCHAR(36) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_prisma_internal_uoc (uocId, internalReference),
  FOREIGN KEY (uocId) REFERENCES CertificationUnit(id) ON DELETE CASCADE,
  FOREIGN KEY (responsibleId) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS PrismaAdjustment (
  id VARCHAR(36) PRIMARY KEY,
  operationId VARCHAR(36) NOT NULL,
  adjustmentType ENUM('CONFIRMATION','REMOVE','ADJUSTMENT') NOT NULL,
  previousVolumeMt DECIMAL(12,3) NULL,
  newVolumeMt DECIMAL(12,3) NULL,
  reason TEXT NOT NULL,
  createdBy VARCHAR(36) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (operationId) REFERENCES PrismaOperation(id) ON DELETE CASCADE,
  FOREIGN KEY (createdBy) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS PrismaAttachment (
  id VARCHAR(36) PRIMARY KEY,
  operationId VARCHAR(36) NOT NULL,
  evidenceId VARCHAR(36) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (operationId) REFERENCES PrismaOperation(id) ON DELETE CASCADE,
  FOREIGN KEY (evidenceId) REFERENCES Evidence(id) ON DELETE CASCADE
);

ALTER TABLE Evidence ADD COLUMN IF NOT EXISTS uocId VARCHAR(36) NULL;
ALTER TABLE Evidence ADD COLUMN IF NOT EXISTS companyName VARCHAR(255) NULL;
ALTER TABLE Evidence ADD COLUMN IF NOT EXISTS supplySourceId VARCHAR(36) NULL;
ALTER TABLE Evidence ADD COLUMN IF NOT EXISTS farmPlotId VARCHAR(36) NULL;
ALTER TABLE Evidence ADD COLUMN IF NOT EXISTS requirementId VARCHAR(36) NULL;
ALTER TABLE Evidence ADD COLUMN IF NOT EXISTS indicator VARCHAR(255) NULL;
ALTER TABLE Evidence ADD COLUMN IF NOT EXISTS responsible VARCHAR(255) NULL;
ALTER TABLE Evidence ADD COLUMN IF NOT EXISTS fileName VARCHAR(255) NULL;
ALTER TABLE Evidence ADD COLUMN IF NOT EXISTS originalFileName VARCHAR(255) NULL;
ALTER TABLE Evidence ADD COLUMN IF NOT EXISTS mimeType VARCHAR(100) NULL;
ALTER TABLE Evidence ADD COLUMN IF NOT EXISTS observations TEXT NULL;
